### ISSUE TITLE
Different options for different source

### ISSUE THREAD

**Issue by nanta122** [MitchTalmadge/discord-echobot#1]
Hi, how can i apply different options (eg. title) for each different source?

For instance, for message coming from server A, it should be titled "server 1" and for message coming from server B, it should be titled "server 2".

I tried to duplicate the code but it is not running. Example:

{
  "token": "mfa.yourtoken-shouldgoherejklsdfhsoiehfseihfseifbisoehfoisefise",
  "redirects": [
    {
      "sources": [
        "123456789321432454"
      ],
      "destinations": [
        "129863219696239848"
      ],
      "options": {
        "title": "Server 1",
        "richEmbed": true,
        "richEmbedColor": 30975,
        "includeSource": true,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true
      }
    }
  ]

"token": "mfa.yourtoken-shouldgoherejklsdfhsoiehfseihfseifbisoehfoisefise",
  "redirects": [
    {
      "sources": [
        "124354366576899678"
      ],
      "destinations": [
        "129863219696239848"
      ],
      "options": {
        "title": "Server 2",
        "richEmbed": true,
        "richEmbedColor": 30975,
        "includeSource": true,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true
      }
    }
  ]
}

Thanks.

**Comment by pagelift-be** [comment]
Like this:

<img width="522" alt="Schermafbeelding 2019-04-30 om 21 09 17" src="https://user-images.githubusercontent.com/49045897/56986926-670cdb00-6b8c-11e9-83b8-8a037418575a.png">

You only have to copy what's between [], but don't forget adding a comma after the last } before you paste the second redirection.

**Comment by MitchTalmadge** [comment]
Thank you @pagelift-be for the nice example!
