### ISSUE TITLE
app couldnt deploy to heroku

### ISSUE THREAD

**Issue by afmfdf90** [MitchTalmadge/discord-echobot#12]
i tried to deploy to heroku and it failed.
https://pastebin.com/FmTds2L4

**Comment by syth88** [comment]
Hi,

I noticed the same error today when trying to deploy it to heroku.
It seems like nowadays Heroku needs to know what version of Node.js to download for any app that is being deployed.

But when adding the node version to the package.json file, this error occurs:
_remote: -----> Node.js app detected
remote: parse error: Expected separator between values at line 8, column 11
remote:  !     Unable to parse package.json
remote:
remote:
remote: -----> Build failed_

So I didn't manage to fix it either.
Any help would be greatly appreciated.

**Comment by MitchTalmadge** [comment]
Some in-range dependencies broke the build. I added CI to catch this next time, and fixed it in master. Sorry for the delay. Let me know if it works for you now. Enjoy!

**Comment by syth88** [comment]
Thank you very much for the quick response/fix, Mitch!
