### ISSUE TITLE
Directing certain channels to a specific channel

### ISSUE THREAD

**Issue by 0xFR0STY** [MitchTalmadge/discord-echobot#19]
Not sure if its possible, but a feature that would direct certain channels to a specific channel instead of all the destinations if that makes sense. So channel A as the source would go to channel C and then channel B would go to channel D instead of how the current config is for channel A and B to go to both channel C and D. Separating channels to go to specific channels.

**Comment by MitchTalmadge** [comment]
This is possible :) In the config just add another redirect section, like this:

```
{
  "token": "mfa.yourtoken-shouldgoherejklsdfhsoiehfseihfseifbisoehfoisefise",
  "redirects": [
    {
      "sources": [
        "A",
      ],
      "destinations": [
        "C"
      ],
      "options": {
        "title": "New Copied Message",
        "richEmbed": true,
        "richEmbedColor": 30975,
        "includeSource": true,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true,
        "copyAttachments": true,
        "minLength": 0,
        "allowList": []
      }
    },
    {
      "sources": [
        "B",
      ],
      "destinations": [
        "D"
      ],
      "options": {
        "title": "New Copied Message",
        "richEmbed": true,
        "richEmbedColor": 30975,
        "includeSource": true,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true,
        "copyAttachments": true,
        "minLength": 0,
        "allowList": []
      }
    }
  ]
}
```

The options have to be specified twice but the benefit is that you can make these two redirect rules work differently if you want.

Lemme know if it works!

**Comment by 0xFR0STY** [comment]
it's coming back with an error. This is my code with the token redacted 
```JSON
{
  "token": "token",
  "redirects": [
    {
      "sources": [
        "789639539433013268",
      ],
      "destinations": [
        "797836617237790771"
      ],
      "options": {
        "title": false,
        "richEmbed": true,
        "richEmbedColor": 30970,
        "includeSource": false,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true,
        "copyAttachments": true,
        "minLength": 0,
        "allowList": []
      }
    },
    {
      "sources": [
        "766449639686799380",
      ],
      "destinations": [
        "797854631791034378"
      ],
      "options": {
        "title": false,
        "richEmbed": true,
        "richEmbedColor": 30970,
        "includeSource": false,
        "removeEveryone": true,
        "removeHere": true,
        "copyRichEmbed": true,
        "copyAttachments": true,
        "minLength": 0,
        "allowList": []
      }
    }
  ]
}
```

**Comment by 0xFR0STY** [comment]
![image](https://user-images.githubusercontent.com/35744421/104130406-3821a300-5336-11eb-9ba9-056caf000e37.png)

**Comment by 0xFR0STY** [comment]
[2021-01-10T17_19_11_917Z-debug.log](https://github.com/MitchTalmadge/discord-echobot/files/5793007/2021-01-10T17_19_11_917Z-debug.log)
This is the debug file

**Comment by MitchTalmadge** [comment]
In each of your sources lists, make sure the last item (which is the only item in this case) does not end with a comma. I see that both of them have commas at the end. JSON is really picky like that :P

**Comment by 0xFR0STY** [comment]
Wow, this is actually legit! The direct channel does work! You should note it somewhere in the documentation! Thanks alot man!
