### ISSUE TITLE
Bot working slowly

### ISSUE THREAD

**Issue by mohdarif7700** [MitchTalmadge/discord-echobot#4]
As many messages are sent in different sources ids at same point of time , then bot is pasting the messages very slowly in the destination id..

Can we make it fast so that it doesn't lat behind... 
Sometimes when 50+ messages are there in the source at a same time , then bot is unable to paste the messages fast.. it is pasting but very slowly...

Can we make the bot FAST?

**Comment by MitchTalmadge** [comment]
The speed of the bot is limited by discord's own API. Try sending 50+ messages at the same time yourself; it will take forever for them to actually send no matter how fast you spam the enter key. If there's a way to make the bot faster then I wouldn't know what it is, sorry!

**Comment by mohdarif7700** [comment]
Thanks for your reply Sir , i am using 3 source channels and 1 destination
channel. In 3 source channels, messages are sent by members fast , but in
my destination it does not paste that messages at that speed rate in which
they are sent...

I noticed that for 1 message it takes approx 1-1.5 sec for pasting into
destination...

Can we make this code by using Python?? Will it increase the speed?

AIM - MY MAIN OBJECTIVE IS TO SEE THE MESSAGES OF 2 TO 3 SOURCE TEXT
CHANNELS IN MY CHANNEL AT THE SAME TIME IN WHICH THEY ARE SENT.

THANKS FOR HELPING ME, SIR  !

**Comment by pagelift-be** [comment]
"Can we make this code by using Python?? Will it increase the speed?" No because the problem is with the Discord API and not the bot.

**Comment by MitchTalmadge** [comment]
Yeah, sorry! This is going about as fast as it can go. The language being used is not the bottleneck. Unless there's some Discord tricks I don't know of I unfortunately can't make the bot faster.
