### ISSUE TITLE
Copying certain type of messages

### ISSUE THREAD

**Issue by mohdarif7700** [MitchTalmadge/discord-echobot#6]
Can we copy only that type of messages which we want to copy ?

like in a text channel.. chats are going on like this....

How it is?
That's true
What you want
1
Hey
2
Bro 
3

In this  , i only want to copy the message 1,2,3 and  not any other thing..
So , how can i do that ?

Where in the code i have to modify?

**Comment by MitchTalmadge** [comment]
I may add pattern matching in the future but for now on your local copy you could modify the method `onDiscordClientMessageReceived` and simply return if the message doesn't match your pattern.
