### ISSUE TITLE
Problem adding multiple redirections

### ISSUE THREAD

**Issue by pagelift-be** [MitchTalmadge/discord-echobot#8]
I need multiple redirections with one source and one destination. I tried adding a second one and according to the output it works:

<img width="511" alt="Schermafbeelding 2019-04-30 om 21 17 17" src="https://user-images.githubusercontent.com/49045897/56987440-b6074000-6b8d-11e9-8e61-cd6193fb5246.png">
<img width="806" alt="Schermafbeelding 2019-04-30 om 21 18 13" src="https://user-images.githubusercontent.com/49045897/56987441-b6074000-6b8d-11e9-951b-e90479a56b8d.png">

However, the second message is not showing up in my server. When I change one of the options, for example includeSource (no matter if it's in the first or second redirect) they DO both show. Any idea why?

**Comment by MitchTalmadge** [comment]
Very interesting, I will test this and let you know. I have a college final tomorrow so I'll try to get to it soon!

**Comment by ahmedwalid05** [comment]
I know it's a bit late to reply here. 
But `lastEcho` variable is what's causing this issue. it will check it before sending in another channel, so if you are trying to send the same message to two locations, it will cause an issue

**Comment by MitchTalmadge** [comment]
Thanks and sorry for the huge delay. This is fixed now, I have removed `lastEcho` and properly use a random nonce instead.

https://github.com/MitchTalmadge/discord-echobot/releases/tag/2.0.0
