### ISSUE TITLE
Copying uploaded images from a message

### ISSUE THREAD

**Issue by syth88** [MitchTalmadge/discord-echobot#9]
Hi,

I've been using the bot for a while now and gotta say I really like it.
It has been doing all I wanted/needed it to do, so thanks for that.

I'm only experiencing one issue:
When the original message contains a image that has been uploaded to Discord (so not via a URL, but directly uploaded from the original poster's device), the bot doesn't copy the image.
Is there a way to do that? I was thinking that every image gets an own URL once it's been uploaded to Discord (for example https://cdn.discordapp.com/attachments/583252052814069774/601410645421981716/testimagediscord.png).

If the bot wouldn't be able to copy the image itself, would it be able to copy the URL of the image instead?

Thanks in advance.

Best regards

**Comment by MitchTalmadge** [comment]
Completed in the latest commit. Please test it out and let me know how it goes! 

Add `"copyAttachments": true` to your config options section to enable this feature. Also documented in the README.

**Comment by syth88** [comment]
This works like a charm, thank you!

**Comment by MitchTalmadge** [comment]
Great to hear!
